-- =========================================================================
-- 015_so_fulfillment_v2_planned.sql
-- Track quantities allocated to active production plans so the fulfillment
-- "pending" column auto-reduces when a plan is created.
--
-- pending = original - dispatched - PLANNED (new)
--
-- planned_qty_kg / planned_qty_units are bumped by plan_v2.create_plan and
-- released by plan_v2.cancel_plan. A CHECK constraint enforces that the
-- triple (original - dispatched - planned) never goes negative — so the
-- backend will reject over-allocation cleanly.
--
-- Generated columns can't have their expressions altered in place, so the
-- pending_qty_* columns are dropped and re-added. Existing data in those
-- columns is regenerated by Postgres automatically.
--
-- Idempotent. Safe to re-run.
-- =========================================================================

-- ── 1. Add the planned-counter columns (default 0, NOT NULL, CHECK >= 0) ──
ALTER TABLE so_fulfillment_v2
    ADD COLUMN IF NOT EXISTS planned_qty_kg NUMERIC(12,3) NOT NULL DEFAULT 0
        CHECK (planned_qty_kg >= 0);

ALTER TABLE so_fulfillment_v2
    ADD COLUMN IF NOT EXISTS planned_qty_units NUMERIC(12,3) NOT NULL DEFAULT 0
        CHECK (planned_qty_units >= 0);

-- ── 2. Recompute pending_qty_kg as a generated column (subtracting planned) ──
ALTER TABLE so_fulfillment_v2 DROP COLUMN IF EXISTS pending_qty_kg;
ALTER TABLE so_fulfillment_v2
    ADD COLUMN pending_qty_kg NUMERIC(12,3)
        GENERATED ALWAYS AS
            (original_qty_kg - dispatched_qty_kg - planned_qty_kg) STORED;

-- ── 3. Same for units. original_qty_units is NULLABLE so the formula
--      cascades NULL when original is unknown; that's the right semantic. ──
ALTER TABLE so_fulfillment_v2 DROP COLUMN IF EXISTS pending_qty_units;
ALTER TABLE so_fulfillment_v2
    ADD COLUMN pending_qty_units NUMERIC(12,3)
        GENERATED ALWAYS AS
            (original_qty_units - dispatched_qty_units - planned_qty_units) STORED;

-- ── 4. Hard guards: never let the effective pending go negative ──
ALTER TABLE so_fulfillment_v2 DROP CONSTRAINT IF EXISTS chk_pending_kg_nonneg;
ALTER TABLE so_fulfillment_v2 ADD CONSTRAINT chk_pending_kg_nonneg
    CHECK (original_qty_kg - dispatched_qty_kg - planned_qty_kg >= 0);

ALTER TABLE so_fulfillment_v2 DROP CONSTRAINT IF EXISTS chk_pending_units_nonneg;
ALTER TABLE so_fulfillment_v2 ADD CONSTRAINT chk_pending_units_nonneg
    CHECK (
        original_qty_units IS NULL
        OR original_qty_units
           - COALESCE(dispatched_qty_units, 0)
           - COALESCE(planned_qty_units, 0) >= 0
    );

-- ── 5. Doc comments ──
COMMENT ON COLUMN so_fulfillment_v2.planned_qty_kg IS
    'Kg cumulatively committed to active (non-cancelled) production plans. '
    'Bumped by plan_v2.create_plan; released by plan_v2.cancel_plan. '
    'Subtracted from pending_qty_kg via the generated column.';
COMMENT ON COLUMN so_fulfillment_v2.planned_qty_units IS
    'Pack count cumulatively committed to active plans. Mirror of planned_qty_kg.';
COMMENT ON COLUMN so_fulfillment_v2.pending_qty_kg IS
    'Auto-computed: original_qty_kg - dispatched_qty_kg - planned_qty_kg. '
    'Hard-bound to >= 0 via chk_pending_kg_nonneg.';
COMMENT ON COLUMN so_fulfillment_v2.pending_qty_units IS
    'Auto-computed: original_qty_units - dispatched_qty_units - planned_qty_units. '
    'NULL when original_qty_units is NULL.';
